[package]
name = "mediaops-home"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
libc.workspace = true
tokio = { workspace = true, default-features = false, features = ["macros", "process", "rt-multi-thread", "signal", "time"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["fmt", "json"] }

[dev-dependencies]
tokio = { workspace = true, default-features = false, features = ["io-util"] }
