[package]
name = "mediaops-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
mediaops-core.workspace = true
prost.workspace = true
thiserror.workspace = true
tonic = { workspace = true, features = ["codegen", "router", "transport"] }
tonic-prost.workspace = true
tracing.workspace = true

[build-dependencies]
tonic-prost-build.workspace = true
