[package]
name = "mediaops-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
blake3.workspace = true
serde = { workspace = true, features = ["derive"] }
similar.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true
